### ISSUE TITLE
Spigot 1.21.1 NoClassDefFoundError: net/minecraft/nbt/Tag

### ISSUE THREAD

**Issue by mhtvsSFrpHdE** [EuSouVoce/FartherViewDistance_1.20.1#12]
Change render distance doesn't seem to work on client  
Also type any viewdistance command and only response is "op"
```
[Server thread/INFO]: [FartherViewDistance] Enabling FartherViewDistance v9.9.2
[Server thread/ERROR]: Error occurred while enabling FartherViewDistance v9.9.2 (Is it up to date?)
java.lang.NoClassDefFoundError: net/minecraft/nbt/Tag
        at xuan.cat.fartherviewdistance.code.branch.v121.Branch_121_Packet.<init>(Branch_121_Packet.java:24) ~[?:?]
        at xuan.cat.fartherviewdistance.code.ChunkIndex.onEnable(ChunkIndex.java:124) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:267) ~[spigot-api-1.21.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342) ~[spigot-api-1.21.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:492) ~[spigot-api-1.21.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_21_R1.CraftServer.enablePlugin(CraftServer.java:575) ~[spigot-1.21.1-R0.1-SNAPSHOT.jar:4300-Spigot-a759b62-7070de8]
        at org.bukkit.craftbukkit.v1_21_R1.CraftServer.enablePlugins(CraftServer.java:489) ~[spigot-1.21.1-R0.1-SNAPSHOT.jar:4300-Spigot-a759b62-7070de8]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:641) ~[spigot-1.21.1-R0.1-SNAPSHOT.jar:4300-Spigot-a759b62-7070de8]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:426) ~[spigot-1.21.1-R0.1-SNAPSHOT.jar:4300-Spigot-a759b62-7070de8]
        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:269) ~[spigot-1.21.1-R0.1-SNAPSHOT.jar:4300-Spigot-a759b62-7070de8]
        at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1017) ~[spigot-1.21.1-R0.1-SNAPSHOT.jar:4300-Spigot-a759b62-7070de8]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[spigot-1.21.1-R0.1-SNAPSHOT.jar:4300-Spigot-a759b62-7070de8]
        at java.base/java.lang.Thread.run(Unknown Source) [?:?]
Caused by: java.lang.ClassNotFoundException: net.minecraft.nbt.Tag
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:160) ~[spigot-api-1.21.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:112) ~[spigot-api-1.21.1-R0.1-SNAPSHOT.jar:?]
        at java.base/java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
        ... 13 more
```

**Comment by mhtvsSFrpHdE** [comment]
`FartherViewDistance` folder and `config.yml` is genereated though

**Comment by EuSouVoce** [comment]
That happend because you were using a spigot server instead of a paper one. Spigot lacks a lot of the improvements and patches that Paper has, also paper uses the mojang mappings now.

**Comment by mhtvsSFrpHdE** [comment]
There is reason to use paper and also reason to stay on spigot. Some choose fabric too because of that. Sad to know this feature won't port to spigot.

**Comment by EuSouVoce** [comment]
Paper now uses the mc native mappings, so there is no more unnecessary obfuscation or delays.The plugin should also work on Spigot because it relies on the nms packets and chunk loading, just change the commands and chunks...

**Comment by mhtvsSFrpHdE** [comment]
I'll pick a time to see if latest version will run on my personal server...
Maybe just at the time the plugin still not fully compatible with 1.21.1
