### ISSUE TITLE
Server crash when attempting to load chunks

### ISSUE THREAD

**Issue by DarkChromaMC** [EuSouVoce/FartherViewDistance_1.20.1#14]
Version: 1.21.1-2329-803bf62 (MC: 1.21.1) (latest version of Purpur for 1.21.1)0
Plugin version: FartherViewDistance v9.9.2

The server crashes during asynchronous chunk handling and occurs when preparing or saving chunk data, leading to a NullPointerException. The crash appears related to FartherViewDistance's handling of extended view distance or chunk-related logic for unloaded chunks. It seems both async preparation and saving fails, causing the server to fallback to synchronous operations and eventually crash.

Steps to Reproduce:
1. Run the FartherViewDistance plugin
2. Load or unload chunks that haven't been generated yet
3. Observe the server logs for chunk save failures and subsequent crash.

Expected Behavior:
Chunks should load and save asynchronously without causing server crashes.

Logs:
```
[04:15:05] [Server thread/ERROR]: [ca.spottedleaf.moonrise.patches.chunk_system.scheduling.NewChunkHolder] Failed to save chunk data (1358,555) in world 'world'
java.lang.NullPointerException: Cannot invoke "it.unimi.dsi.fastutil.objects.ObjectArrayList.get(int)" because "this.wrapped" is null
	at it.unimi.dsi.fastutil.objects.Object2ObjectOpenHashMap$MapIterator.nextEntry(Object2ObjectOpenHashMap.java:637) ~[fastutil-8.5.12.jar:?]
	at it.unimi.dsi.fastutil.objects.Object2ObjectOpenHashMap$KeyIterator.next(Object2ObjectOpenHashMap.java:1038) ~[fastutil-8.5.12.jar:?]
	at java.base/java.util.AbstractCollection.addAll(AbstractCollection.java:337) ~[?:?]
	at net.minecraft.world.level.chunk.ChunkAccess.getBlockEntitiesPos(ChunkAccess.java:242) ~[universe-1.21.1.jar:1.21.1-d624699]
	at net.minecraft.world.level.chunk.storage.ChunkSerializer.saveChunk(ChunkSerializer.java:483) ~[universe-1.21.1.jar:1.21.1-d624699]
	at net.minecraft.world.level.chunk.storage.ChunkSerializer.write(ChunkSerializer.java:389) ~[universe-1.21.1.jar:1.21.1-d624699]
	at ca.spottedleaf.moonrise.patches.chunk_system.scheduling.NewChunkHolder.saveChunk(NewChunkHolder.java:1809) ~[universe-1.21.1.jar:1.21.1-d624699]
	at ca.spottedleaf.moonrise.patches.chunk_system.scheduling.NewChunkHolder.unloadStage2(NewChunkHolder.java:904) ~[universe-1.21.1.jar:1.21.1-d624699]
	at ca.spottedleaf.moonrise.patches.chunk_system.scheduling.ChunkHolderManager.processUnloads(ChunkHolderManager.java:1154) ~[universe-1.21.1.jar:1.21.1-d624699]
	at net.minecraft.server.level.ChunkMap.processUnloads(ChunkMap.java:425) ~[universe-1.21.1.jar:1.21.1-d624699]
	at net.minecraft.server.level.ChunkMap.tick(ChunkMap.java:415) ~[universe-1.21.1.jar:1.21.1-d624699]
	at net.minecraft.server.level.ServerChunkCache.tick(ServerChunkCache.java:417) ~[universe-1.21.1.jar:1.21.1-d624699]
	at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:685) ~[universe-1.21.1.jar:1.21.1-d624699]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1768) ~[universe-1.21.1.jar:1.21.1-d624699]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:489) ~[universe-1.21.1.jar:1.21.1-d624699]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1584) ~[universe-1.21.1.jar:1.21.1-d624699]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1289) ~[universe-1.21.1.jar:1.21.1-d624699]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:334) ~[universe-1.21.1.jar:1.21.1-d624699]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
[04:15:05] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.ReportedException: Exception ticking world
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1773) ~[universe-1.21.1.jar:1.21.1-d624699]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:489) ~[universe-1.21.1.jar:1.21.1-d624699]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1584) ~[universe-1.21.1.jar:1.21.1-d624699]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1289) ~[universe-1.21.1.jar:1.21.1-d624699]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:334) ~[universe-1.21.1.jar:1.21.1-d624699]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "it.unimi.dsi.fastutil.objects.ObjectArrayList.get(int)" because "this.wrapped" is null
	at it.unimi.dsi.fastutil.objects.Object2ObjectOpenHashMap$MapIterator.nextEntry(Object2ObjectOpenHashMap.java:637) ~[fastutil-8.5.12.jar:?]
	at it.unimi.dsi.fastutil.objects.Object2ObjectOpenHashMap$ValueIterator.next(Object2ObjectOpenHashMap.java:1141) ~[fastutil-8.5.12.jar:?]
	at net.minecraft.server.level.ServerLevel.unload(ServerLevel.java:1583) ~[universe-1.21.1.jar:1.21.1-d624699]
	at ca.spottedleaf.moonrise.patches.chunk_system.scheduling.NewChunkHolder.unloadStage2(NewChunkHolder.java:910) ~[universe-1.21.1.jar:1.21.1-d624699]
	at ca.spottedleaf.moonrise.patches.chunk_system.scheduling.ChunkHolderManager.processUnloads(ChunkHolderManager.java:1154) ~[universe-1.21.1.jar:1.21.1-d624699]
	at net.minecraft.server.level.ChunkMap.processUnloads(ChunkMap.java:425) ~[universe-1.21.1.jar:1.21.1-d624699]
	at net.minecraft.server.level.ChunkMap.tick(ChunkMap.java:415) ~[universe-1.21.1.jar:1.21.1-d624699]
	at net.minecraft.server.level.ServerChunkCache.tick(ServerChunkCache.java:417) ~[universe-1.21.1.jar:1.21.1-d624699]
	at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:685) ~[universe-1.21.1.jar:1.21.1-d624699]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1768) ~[universe-1.21.1.jar:1.21.1-d624699]
	... 5 more
[04:15:05] [Server thread/ERROR]: This crash report has been saved to: /home/container/crash-reports/crash-2024-11-26_04.15.05-server.txt
[04:15:05] [Server thread/INFO]: Stopping server
```

[crash-2024-11-26_04.15.05-server.txt](https://github.com/user-attachments/files/17913036/crash-2024-11-26_04.15.05-server.txt)

Can offer $50 USD donation to someone who can fix this issue that happens sometimes for us. Please let me know if any further information is needed!

**Comment by DarkChromaMC** [comment]
Just want to clarify this was caused by GPETS player sit feature when a player was in vanish. Sorry for any inconveniences casued!
