### ISSUE TITLE
Plz, update 1.21 support

### ISSUE THREAD

**Issue by 44wrw44** [EuSouVoce/FartherViewDistance_1.20.1#3]
```
[11:01:46] [Server thread/ERROR]: Error occurred while enabling FartherViewDistance v9.8.4 (Is it up to date?)
java.lang.IllegalArgumentException: Unsupported MC version:  |  Bukkit Version:1.21-R0.1-SNAPSHOT
	at FartherViewDistance.jar/xuan.cat.fartherviewdistance.code.ChunkIndex.onEnable(ChunkIndex.java:120) ~[FartherViewDistance.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[purpur-1.21.jar:1.21-2240-c0f5e78]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[purpur-1.21.jar:1.21-2240-c0f5e78]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:643) ~[purpur-1.21.jar:1.21-2240-c0f5e78]
	at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:592) ~[purpur-1.21.jar:1.21-2240-c0f5e78]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:693) ~[purpur-1.21.jar:1.21-2240-c0f5e78]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:455) ~[purpur-1.21.jar:1.21-2240-c0f5e78]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:361) ~[purpur-1.21.jar:1.21-2240-c0f5e78]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1171) ~[purpur-1.21.jar:1.21-2240-c0f5e78]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:332) ~[purpur-1.21.jar:1.21-2240-c0f5e78]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

**Comment by EuSouVoce** [comment]
Support was added in v9.9.0 and lightning errors were fixed in v9.9.2
