### ISSUE TITLE
Console spam on 1.21

### ISSUE THREAD

**Issue by Australiec** [EuSouVoce/FartherViewDistance_1.20.1#9]
This error spamming in my server console.  There were no obvious problems in operation related to this error. I using latest Purpur 1.21 build (1.21-2280)

The same problem occurs in a large number of plugins - https://github.com/EngineHub/WorldGuard/issues/2111

```
Could not pass event PlayerTeleportEvent to FartherViewDistance v9.9.2
java.lang.NullPointerException: Cannot invoke "org.bukkit.Location.getWorld()" because "move" is null
        at FartherViewDistance.jar/xuan.cat.fartherviewdistance.code.ChunkServer.unloadView(ChunkServer.java:686) ~[FartherViewDistance.jar:?]
        at FartherViewDistance.jar/xuan.cat.fartherviewdistance.code.ChunkEvent.event(ChunkEvent.java:48) ~[FartherViewDistance.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor345.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:1.21-2280-930003b]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.21.jar:1.21-2280-930003b]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[purpur-1.21.jar:1.21-2280-930003b]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.level.ServerPlayer.changeDimension(ServerPlayer.java:1413) ~[purpur-1.21.jar:1.21-2280-930003b]
        at net.minecraft.world.entity.Entity.handlePortal(Entity.java:3326) ~[purpur-1.21.jar:1.21-2280-930003b]
        at net.minecraft.world.entity.Entity.baseTick(Entity.java:898) ~[purpur-1.21.jar:1.21-2280-930003b]
        at net.minecraft.world.entity.LivingEntity.baseTick(LivingEntity.java:447) ~[purpur-1.21.jar:1.21-2280-930003b]
        at net.minecraft.world.entity.Entity.tick(Entity.java:871) ~[purpur-1.21.jar:1.21-2280-930003b]
        at net.minecraft.world.entity.LivingEntity.tick(LivingEntity.java:3200) ~[purpur-1.21.jar:1.21-2280-930003b]
        at net.minecraft.world.entity.player.Player.tick(Player.java:317) ~[purpur-1.21.jar:1.21-2280-930003b]
        at net.minecraft.server.level.ServerPlayer.doTick(ServerPlayer.java:854) ~[purpur-1.21.jar:1.21-2280-930003b]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.tick(ServerGamePacketListenerImpl.java:360) ~[purpur-1.21.jar:1.21-2280-930003b]
        at net.minecraft.network.Connection.tick(Connection.java:647) ~[purpur-1.21.jar:1.21-2280-930003b]
        at net.minecraft.server.network.ServerConnectionListener.tick(ServerConnectionListener.java:242) ~[purpur-1.21.jar:1.21-2280-930003b]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1860) ~[purpur-1.21.jar:1.21-2280-930003b]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:509) ~[purpur-1.21.jar:1.21-2280-930003b]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1634) ~[purpur-1.21.jar:1.21-2280-930003b]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1334) ~[purpur-1.21.jar:1.21-2280-930003b]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:333) ~[purpur-1.21.jar:1.21-2280-930003b]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

**Comment by EuSouVoce** [comment]
Is it still happening on v10.0.0 or v10.1.0?
Reopen if it is.
